name: dent_mobile
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  adaptive_action_sheet: ^2.0.1
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  custom_radio_grouped_button: ^2.1.2+2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_staggered_grid_view: ^0.6.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  injectable_generator: ^1.5.3
  read_more_less: ^0.0.4
  syncfusion_flutter_sliders: ^20.1.61

dev_dependencies:
  auto_route: ^4.0.1
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  google_fonts: ^3.0.1
  intl: ^0.17.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/